package scripts_test

import (
	"bytes"
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// generation is what scripts/catalogue.go answers a specification with.
type generation struct {
	code   int
	stderr string
	// What it wrote, "" where it wrote nothing.
	source string
}

func buildGenerator(t *testing.T) string {
	t.Helper()
	program := filepath.Join(t.TempDir(), "catalogue")
	output, err := exec.CommandContext(t.Context(), "go", "build", "-o", program, "catalogue.go").CombinedOutput()
	require.NoError(t, err, "%s", output)
	return program
}

func generate(t *testing.T, program, specification string) generation {
	t.Helper()
	dir := t.TempDir()
	input, output := filepath.Join(dir, "openapi.json"), filepath.Join(dir, "catalogue.gen.go")
	require.NoError(t, os.WriteFile(input, []byte(specification), 0o600))
	// Without its check a schema that extends itself is walked for ever.
	ctx, cancel := context.WithTimeout(t.Context(), time.Minute)
	defer cancel()
	var stderr bytes.Buffer
	run := exec.CommandContext(ctx, program, input, output)
	run.Stderr = &stderr
	got := generation{}
	var exit *exec.ExitError
	if err := run.Run(); errors.As(err, &exit) {
		got.code = exit.ExitCode()
	} else {
		require.NoError(t, err)
	}
	got.stderr = stderr.String()
	if source, err := os.ReadFile(output); err == nil {
		got.source = string(source)
	}
	return got
}

func TestCatalogueWritesEveryShapeTheSpecificationHas(t *testing.T) {
	t.Parallel()
	const specification = `{"components":{"schemas":{
		"IssueCustomField":{"type":"object","description":"A field of an issue.",
			"properties":{"$type":{"type":"string","readOnly":true},"value":{"type":"object"}},
			"discriminator":{"propertyName":"$type","mapping":{
				"IssueCustomField":"#/components/schemas/IssueCustomField",
				"SingleValueIssueCustomField":"#/components/schemas/DatabaseSingleValueIssueCustomField"}}},
		"DatabaseSingleValueIssueCustomField":{"allOf":[{"$ref":"#/components/schemas/IssueCustomField"}]},
		"Member":{"type":"object","properties":{"id":{"type":"string"}}},
		"User":{"allOf":[{"$ref":"#/components/schemas/Member"},{"type":"object","properties":{
			"login":{"type":"string","nullable":true},
			"description":{"type":"string"},
			"online":{"type":"boolean"},
			"created":{"type":"integer","format":"int64"},
			"size":{"type":"integer","format":"int64"},
			"weight":{"type":"number","format":"float"},
			"level":{"type":"integer","format":"int32","enum":[1,2]},
			"manager":{"$ref":"#/components/schemas/User"},
			"groups":{"type":"array","items":{"$ref":"#/components/schemas/Member"}},
			"tags":{"type":"array","items":{"type":"string","format":"id"}}}}]}
	}}}`
	const source = `// Code generated by scripts/catalogue.go from api/openapi.json. DO NOT EDIT.

package youtrack

func catalogue() map[string]schema {
	return map[string]schema{
		"IssueCustomField": {properties: map[string]string{
			"$type": "",
			"value": "{}",
		}},
		"Member": {properties: map[string]string{
			"id": "",
		}},
		"SingleValueIssueCustomField": {parent: "IssueCustomField"},
		"User": {parent: "Member", properties: map[string]string{
			"created":     "!time",
			"description": "!text",
			"groups":      "[]Member",
			"level":       "",
			"login":       "",
			"manager":     "User",
			"online":      "",
			"size":        "",
			"tags":        "[]",
			"weight":      "",
		}},
	}
}
`

	got := generate(t, buildGenerator(t), specification)

	assert.Equal(t, generation{source: source}, got)
}

func TestCatalogueRefusesAShapeItDoesNotRead(t *testing.T) {
	t.Parallel()
	program := buildGenerator(t)
	tests := []struct {
		name          string
		specification string
	}{
		{
			name:          "a key it does not know on a schema",
			specification: `{"components":{"schemas":{"User":{"type":"object","required":["login"],"properties":{"login":{"type":"string"}}}}}}`,
		},
		{
			name: "a key it does not know on a member of allOf",
			specification: `{"components":{"schemas":{"Member":{"type":"object"},
				"User":{"allOf":[{"$ref":"#/components/schemas/Member"},{"type":"object","required":["login"],"properties":{"login":{"type":"string"}}}]}}}}`,
		},
		{
			name:          "a key it does not know on a property",
			specification: `{"components":{"schemas":{"User":{"type":"object","properties":{"login":{"type":"string","minLength":1}}}}}}`,
		},
		{
			name:          "a key it does not know on the items of a list",
			specification: `{"components":{"schemas":{"User":{"type":"object","properties":{"tags":{"type":"array","items":{"type":"string","enum":["a"]}}}}}}}`,
		},
		{
			name: "a second schema to extend in allOf",
			specification: `{"components":{"schemas":{"Member":{"type":"object"},"Person":{"type":"object"},
				"User":{"allOf":[{"$ref":"#/components/schemas/Member"},{"$ref":"#/components/schemas/Person"}]}}}}`,
		},
		{
			name: "a second object in allOf",
			specification: `{"components":{"schemas":{"Member":{"type":"object"},
				"User":{"allOf":[{"$ref":"#/components/schemas/Member"},{"type":"object"},{"type":"object"}]}}}}`,
		},
		{
			name: "allOf beside a type of the schema's own",
			specification: `{"components":{"schemas":{"Member":{"type":"object"},
				"User":{"type":"object","allOf":[{"$ref":"#/components/schemas/Member"}]}}}}`,
		},
		{
			name:          "allOf that extends no schema",
			specification: `{"components":{"schemas":{"User":{"allOf":[{"type":"object","properties":{"login":{"type":"string"}}}]}}}}`,
		},
		{
			name:          "a schema that is not an object",
			specification: `{"components":{"schemas":{"Login":{"type":"string"}}}}`,
		},
		{
			name:          "a list of objects of no schema",
			specification: `{"components":{"schemas":{"User":{"type":"object","properties":{"groups":{"type":"array","items":{"type":"object"}}}}}}}`,
		},
		{
			name:          "a discriminator on another property",
			specification: `{"components":{"schemas":{"Member":{"type":"object","properties":{"kind":{"type":"string"}},"discriminator":{"propertyName":"kind"}}}}}`,
		},
		{
			name:          "a property that refers to nothing",
			specification: `{"components":{"schemas":{"User":{"type":"object","properties":{"manager":{"$ref":"#/components/schemas/Nobody"}}}}}}`,
		},
		{
			name:          "the items of a list that refer to nothing",
			specification: `{"components":{"schemas":{"User":{"type":"object","properties":{"groups":{"type":"array","items":{"$ref":"#/components/schemas/Nobody"}}}}}}}`,
		},
		{
			name:          "allOf that extends nothing",
			specification: `{"components":{"schemas":{"User":{"allOf":[{"$ref":"#/components/schemas/Nobody"}]}}}}`,
		},
		{
			name:          "a discriminator that maps to nothing",
			specification: `{"components":{"schemas":{"Member":{"type":"object","discriminator":{"propertyName":"$type","mapping":{"User":"#/components/schemas/Nobody"}}}}}}`,
		},
		{
			name: "schemas that extend each other",
			specification: `{"components":{"schemas":{"Member":{"allOf":[{"$ref":"#/components/schemas/User"}]},
				"User":{"allOf":[{"$ref":"#/components/schemas/Member"}]}}}}`,
		},
		{
			name:          "an int64 property whose name is in neither class",
			specification: `{"components":{"schemas":{"Issue":{"type":"object","properties":{"bogusTotal":{"type":"integer","format":"int64"}}}}}}`,
		},
		{
			name:          "a list of int64 whose name is in neither class",
			specification: `{"components":{"schemas":{"Issue":{"type":"object","properties":{"bogusTotals":{"type":"array","items":{"type":"integer","format":"int64"}}}}}}}`,
		},
		{
			name: "a $type two discriminators give to two schemas",
			specification: `{"components":{"schemas":{"Project":{"type":"object"},"User":{"type":"object"},
				"Folder":{"type":"object","discriminator":{"propertyName":"$type","mapping":{"Item":"#/components/schemas/Project"}}},
				"Group":{"type":"object","discriminator":{"propertyName":"$type","mapping":{"Item":"#/components/schemas/User"}}}}}}`,
		},
		{
			name: "a $type that another schema has for its name",
			specification: `{"components":{"schemas":{"Person":{"type":"object"},"User":{"type":"object"},
				"Member":{"type":"object","discriminator":{"propertyName":"$type","mapping":{"Person":"#/components/schemas/User"}}}}}}`,
		},
		{
			name: "a schema discriminators give two $type",
			specification: `{"components":{"schemas":{"User":{"type":"object"},
				"Folder":{"type":"object","discriminator":{"propertyName":"$type","mapping":{"Member":"#/components/schemas/User"}}},
				"Group":{"type":"object","discriminator":{"propertyName":"$type","mapping":{"Person":"#/components/schemas/User"}}}}}}`,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			got := generate(t, program, tc.specification)

			assert.Equal(t, 1, got.code)
			assert.NotEmpty(t, got.stderr)
			assert.Empty(t, got.source)
		})
	}
}
