name: ci

on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make go

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make build VERSION="v0.0.0.$GITHUB_RUN_NUMBER"
      - run: |
          ./bin/ytrack --version | grep -qx "version: \"v0.0.0.$GITHUB_RUN_NUMBER\""
          ./bin/ytrack --version | grep -qx "revision: \"$GITHUB_SHA\""

  release:
    needs: [go, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          commit_date=$(git show -s --format=%cI HEAD)
          echo "VERSION=v$(date -u -d "$commit_date" +%y.%-m.%-d).$GITHUB_RUN_NUMBER" >>"$GITHUB_ENV"
      - run: make dist VERSION="$VERSION"
      - run: |
          ./dist/ytrack-linux-amd64 --version | grep -qx "version: \"$VERSION\""
      - run: gh release create "$VERSION" dist/* --target "$GITHUB_SHA" --title "ytrack $VERSION" --notes "Собран из $GITHUB_SHA."
        env:
          GH_TOKEN: ${{ github.token }}
